### ISSUE TITLE
css chunk doesn't load for child app

### ISSUE THREAD

**Issue by rkolec** [Kizmar/single-spa-cra2#1]
Hi! Thanks for sharing this app. I have similar problem to solve. 

I've found one issue. In this case the main css chunk is not loaded for child application. Do you have any solution or advice? Thanks!

**Comment by Kizmar** [comment]
Three years later I just noticed this issue. It's obviously been a while since I worked on this proof of concept. I don't plan on doing anything more with this repo. Eventually I will be revisiting this project to update libraries, test more thoroughly, and hopefully start implementing it. That will likely be many many months from now though.
